name: Terraform Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - "iac/**"
      - ".github/workflows/terraform-deploy.yaml"

  push:
    branches:
      - main
    paths:
      - "iac/**"
      - ".github/workflows/terraform-deploy.yaml"

  workflow_dispatch:
    inputs:
      action:
        description: "Select Terraform action"
        required: true
        type: choice
        default: apply
        options:
          - destroy
          - apply


permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: iac

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0z
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      # PRs -> Plan only
      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan

      # Merge to main -> Apply
      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve

      # Manual execution -> Destroy
      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve